import { TeamMember } from "../types/members";

export const teamMembers: TeamMember[] = [
  {
    id: "m1",
    name: "Alice Johnson",
    username: "@alice",
    avatar: "/avatars/Fiona.jpeg",
    email: "alice.j@example.com",
    status: ["active", "away"],
    role: "UX Designer",
    teams: ["design", "product", "marketing", "sales", "hr", "finance", "develop"],
  },
  {
    id: "m2",
    name: "Bob Williams",
    username: "@bob",
    avatar: "/avatars/Fiona.jpeg",
    email: "bob.w@example.com",
    status: ["active", "onleave"], // “on leave” → “onleave” (to match your type)
    role: "Product Manager",
    teams: ["design", "product", "marketing", "sales", "hr", "finance", "develop"],
  },
  {
    id: "m3",
    name: "Charlie Brown",
    username: "@charlie",
    avatar: "/avatars/Fiona.jpeg",
    email: "charlie.b@example.com",
    status: ["active", "away"],
    role: "Marketing Specialist",
    teams: ["design", "product", "marketing", "sales", "hr", "finance", "develop"],
  },
  {
    id: "m4",
    name: "Diana Miller",
    username: "@diana",
    avatar: "/avatars/Fiona.jpeg",
    email: "diana.m@example.com",
    status: ["active", "away"],
    role: "Frontend Developer",
    teams: ["design", "product", "marketing", "sales", "hr", "finance", "develop"],
  },
  {
    id: "m5",
    name: "Edward Davis",
    username: "@edward",
    avatar: "/avatars/Fiona.jpeg",
    email: "edward.d@example.com",
    status: ["terminated"],
    role: "SEO Manager",
    teams: ["design", "product", "marketing", "sales", "hr", "finance", "develop"],
  },
  {
    id: "m6",
    name: "Fiona Garcia",
    username: "@fiona",
    avatar: "/avatars/Fiona.jpeg",
    email: "fiona.g@example.com",
    status: ["away"],
    role: "Graphic Designer",
    teams: ["design", "product", "marketing", "sales", "hr", "finance", "develop"],
  },
  {
    id: "m7",
    name: "Sarah Johnson",
    username: "@sarah",
    avatar: "/avatars/Fiona.jpeg",
    email: "sarah@company.com",
    status: ["active"],
    role: "UI Designer",
    teams: ["design", "product", "marketing", "sales", "hr", "finance", "develop"],
  },
  {
    id: "m8",
    name: "David Lee",
    username: "@david",
    avatar: "/avatars/Fiona.jpeg",
    email: "david@company.com",
    status: ["donotdisturb"], // “do not disturb” → “donotdisturb” (to match your SCSS)
    role: "Frontend Dev",
    teams: ["design", "product", "marketing", "sales", "hr", "finance", "develop"],
  },
  {
    id: "m9",
    name: "Maria Gomez",
    username: "@maria",
    avatar: "/avatars/Fiona.jpeg",
    email: "maria@company.com",
    status: ["busy", "away"],
    role: "Product Manager",
    teams: ["design", "product", "marketing", "sales", "hr", "finance", "develop"],
  },
];
